{{- $existingCatalog := lookup "operators.coreos.com/v1alpha1" "CatalogSource" "openshift-marketplace" "ibm-operator-catalog"}}
{{- if not $existingCatalog}}
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: {{.Values.catalog.name}}
  namespace: openshift-marketplace
  annotations:
    argocd.argoproj.io/sync-wave: "10"  
spec:
  displayName: {{.Values.catalog.displayName}}
  sourceType: grpc
  image: {{.Values.catalog.image}}
{{- end}}   