gitops:
  namespaceScoped: true

catalog:
  name: ibm-operator-catalog
  displayName: IBM operator Catalog
  image: icr.io/cpopen/ibm-operator-catalog

subscription:
  wsaOperatorNamespace: websphere-automation
  channel: v1.12
  installPlanApproval: Automatic
  wsaInstanceNamespace: websphere-automation

operatorNamespace: websphere-automation

commonServicesNamespace: websphere-automation

licensingNamespace: ibm-licensing

certManagerNamespace: cert-manager

wsaHealth:
  spec:
    license:
      accept: true
    replicas: 1

wsaSecure:
  spec:
    license:
      accept: true
    replicas: 1

wsa:
  spec:
    commonServices:
      registryNamespace: websphere-automation
    license:
      accept: true
    replicas: 1
    dataStore:
      resources:
        limits:
          cpu: '2'
          memory: 2Gi
        requests:
          cpu: '1'
          ephemeral-storage: 100Mi
          memory: 1Gi
    events:
      kafka:
        resources:
          limits:
            cpu: '2'
            memory: 5Gi
          requests:
            cpu: '2'
            memory: 5Gi
      zookeeper:
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: '1'
            memory: 2Gi
